FROM python:3.10-slim

WORKDIR /app

# system deps for wheel builds
RUN apt-get update && apt-get install -y build-essential && rm -rf /var/lib/apt/lists/*

COPY app/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# copy app
COPY app /app/app

WORKDIR /app/app

# Expose port
EXPOSE 8000

# Create DB on startup (will be created by app)
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--workers", "1"]
